### ISSUE TITLE
[Idea] Put a message like "Press Start buttom to commence the backup/restore"

### ISSUE THREAD

**Issue by RY0M43CH1Z3N** [joel16/VitaBackup#1]

**Comment by joel16** [comment]
Yes I've been contemplating on doing that :p

**Comment by RY0M43CH1Z3N** [comment]
Thank you, and last (idea), add more roots where save the backup (like uma0:, sd0 and other writtable partitions), if you answer this, you can close this issue, thank you for listen to the users.

**Comment by joel16** [comment]
You can add whatever path you want to backup in ur0:/data/VitaBackup/path.txt
Instructions have been added. https://github.com/joel16/VitaBackup/commit/3a02a682e7145d8831b1e6c29afb042f8b323bc2
