### ISSUE TITLE
Overwrite file when the same name appear twice

### ISSUE THREAD

**Issue by UnopposedForce91** [joel16/VitaBackup#3]
When i was backing up my vita i notice that there is a missing folder which is savedata in the user folder, after looking carefully in the path.txt i saw that my Adrenaline saves (savedata) folder overwrite my savedata in the user, because my Adrenaline savedata was after the user one so it was saved .
I think the solution is if a folder with the same name appear, the .tar.zip should name like this :
Savedata-20XX-XX-XX-(Number of the repeated file).tar.zip

**Comment by joel16** [comment]
I don't really maintain this as much anymore since I'm busy with a bunch of other projects. The most you'd be able to do now is to rename the .tar.zip file from vitashell or something.

**Comment by UnopposedForce91** [comment]
Ok Thanks for creating the homebrew, Even if it has some problems that doesnt mean its not cool.
If you have a some time later then perfect! , if you drop the support of the homebrew then i guess its ok  because it's cool, I am looking for next version incase you change your mind :)
